# These are all defaults for now. Descriptions for these settings: https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github#config.yaml-schema
have_fun: false
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: false
    include_drafts: true
ignore_patterns: []

